services:
  blog_service:
    platform: linux/amd64
    container_name: blog_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5555:5555
    volumes:
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - db_service
  db_service:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_container
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.mysql
volumes:
  db_data:
